name: Deploy

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set environment variables
              run: |
                  echo "NEXT_PUBLIC_COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
                  echo "NEXT_PUBLIC_APP_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
